[package]
name = "git-ronin"
description = "Git Ronin desktop app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
getrandom = "0.3"
ignore = "0.4"
notify = "8"
ronin-config.workspace = true
ronin-git.workspace = true
serde.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"

[dev-dependencies]
tempfile.workspace = true
