// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";
import type { Capabilities } from "./Capabilities";

export type AccountView = { account: Account, capabilities: Capabilities, 
/**
 * A token is available (in the keyring or, failing that, in memory).
 */
signedIn: boolean, };
