// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderKind } from "./ProviderKind";

export type Account = { 
/**
 * Stable identifier; also names the account's keyring entry.
 */
id: string, kind: ProviderKind, 
/**
 * Web address of the service, e.g. `https://github.com`, or
 * `https://dev.azure.com/<organization>` for Azure DevOps.
 */
url: string, 
/**
 * The account's user name on the service.
 */
username: string, 
/**
 * Display name.
 */
name: string, avatarUrl: string, 
/**
 * The service's own id for the user (Bitbucket and Azure DevOps need it).
 */
userId: string, 
/**
 * For services that take a user name with the token (Bitbucket Cloud
 * and Jira Cloud use the Atlassian email); empty for bearer tokens.
 */
login: string, 
/**
 * The profile the account belongs to.
 */
profile: string, 
/**
 * The OAuth application the token came from; empty for personal
 * access tokens. Needed to refresh expiring tokens.
 */
oauthClientId: string, };
