// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * This build and how it is updated.
 */
export type AppInfo = { version: string, 
/**
 * How the app was installed, e.g. "AppImage" or "Flatpak".
 */
install: string, 
/**
 * Why the app can't update itself; `None` when it can.
 */
updatesUnavailable: string | null, };
