// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AvailableUpdate = { version: string, 
/**
 * Release notes.
 */
notes: string, 
/**
 * RFC 3339.
 */
date: string | null, };
