// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BisectState = { 
/**
 * What git calls bad and good commits: "bad"/"good" unless the
 * bisect was started with other terms.
 */
badTerm: string, goodTerm: string, bad: string | null, good: Array<string>, skipped: Array<string>, 
/**
 * Commits that may still be the first bad one, the bad one included.
 * Zero until both a bad and a good commit are known.
 */
remaining: number, 
/**
 * Found: the first bad commit.
 */
firstBad: string | null, 
/**
 * Only skipped commits are left to test, so it can't narrow further.
 */
stuck: boolean, };
