// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BlameLine = { 
/**
 * Index into `commits`.
 */
commit: number, 
/**
 * The line's number in that commit's version of the file.
 */
origLine: number, 
/**
 * Without the line ending; a `\r` of CRLF files is kept.
 */
text: string, };
