// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlameCommit } from "./BlameCommit";
import type { BlameLine } from "./BlameLine";

export type Blame = { 
/**
 * Each commit once, in order of first appearance.
 */
commits: Array<BlameCommit>, lines: Array<BlameLine>, };
