// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BlameCommit = { 
/**
 * All zeros for lines not committed yet.
 */
oid: string, authorName: string, authorEmail: string, time: number, summary: string, 
/**
 * The file's path in that commit, which differs after a rename.
 */
path: string, };
