// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A version of a file with uncommitted changes.
 */
export type BlobSource = "head" | "index" | "worktree";
