// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a service supports, so the UI only offers what works.
 */
export type Capabilities = { repos: boolean, fork: boolean, pullRequests: boolean, approve: boolean, draft: boolean, issues: boolean, ci: boolean, sshKeys: boolean, 
/**
 * Sign in through the browser (OAuth device flow) as well as with a token.
 */
deviceFlow: boolean, };
