// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A setting that differs between two documents.
 */
export type Change = { key: string, 
/**
 * `None`: not set on this side.
 */
current: string | null, incoming: string | null, };
