// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckState } from "./CheckState";

export type Check = { name: string, state: CheckState, description: string | null, url: string | null, };
