// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Check } from "./Check";
import type { CheckState } from "./CheckState";

export type CiStatus = { 
/**
 * All checks combined; `None` when there are none.
 */
state: CheckState | null, checks: Array<Check>, };
