// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommitOptions = { 
/**
 * Replace the HEAD commit instead of adding one.
 */
amend: boolean, 
/**
 * Add a `Signed-off-by` trailer.
 */
signoff: boolean, 
/**
 * Skip the pre-commit and commit-msg hooks.
 */
noVerify: boolean, };
