// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommitResult = { 
/**
 * The new HEAD.
 */
oid: string, 
/**
 * What hooks (or git's warnings) printed; git itself is quiet.
 */
output: string, };
