// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileChange } from "./FileChange";
import type { Signature } from "./Signature";

export type CommitDetail = { oid: string, parents: Array<string>, author: Signature, committer: Signature, message: string, 
/**
 * Changes relative to the first parent (or to nothing, for root commits).
 */
files: Array<FileChange>, };
