// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileChange } from "./FileChange";
import type { Signature } from "./Signature";

export type CommitDetail = { oid: string, parents: Array<string>, author: Signature, committer: Signature, message: string, 
/**
 * Changes relative to the first parent (or to nothing, for root commits).
 */
files: Array<FileChange>, 
/**
 * Why `files` is empty when listing changes failed (e.g. a partial clone
 * that can't fetch the blobs). The rest of the detail is still valid.
 */
filesError: string | null, };
