// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Local } from "./Local";
import type { Portable } from "./Portable";

export type Config = { portable: Portable, local: Local, };
