// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictSide } from "./ConflictSide";
import type { MergeChunk } from "./MergeChunk";

/**
 * A conflicted file as the editor shows it.
 */
export type Conflict = { path: string, 
/**
 * The checked-out side: the current branch, or for a rebase the
 * branch being rebased onto.
 */
ours: ConflictSide, 
/**
 * The side being brought in.
 */
theirs: ConflictSide, 
/**
 * Whether the file existed in the common ancestor.
 */
hasBase: boolean, 
/**
 * Both sides are text, so they can be merged chunk by chunk.
 */
text: boolean, 
/**
 * git's merge of the two sides; empty unless `text`.
 */
chunks: Array<MergeChunk>, };
