// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConflictSide = { 
/**
 * E.g. a branch name, or a short commit id and summary.
 */
label: string, 
/**
 * False when this side deleted the file.
 */
present: boolean, };
