// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceCode } from "./DeviceCode";

export type DeviceStart = { flow: number, code: DeviceCode, };
