// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the user needs to authorize the app.
 */
export type DeviceCode = { userCode: string, verificationUri: string, 
/**
 * The verification page with the code already filled in, if offered.
 */
verificationUriComplete: string | null, expiresIn: number, 
/**
 * Seconds to wait between polls.
 */
interval: number, };
