// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineKind } from "./LineKind";

export type DiffLine = { kind: LineKind, oldLine: number | null, newLine: number | null, 
/**
 * The line without its `\n`. A `\r` from CRLF files is kept, so hunks
 * can be turned back into patches that apply.
 */
text: string, 
/**
 * Followed by "\ No newline at end of file".
 */
noNewline: boolean, };
