// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineKind } from "./LineKind";

export type DiffLine = { kind: LineKind, oldLine: number | null, newLine: number | null, text: string, 
/**
 * Followed by "\ No newline at end of file".
 */
noNewline: boolean, };
