// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeKind } from "./EdgeKind";

/**
 * A line segment within one row. Rows are drawn independently, so each edge
 * spans at most one row: top edge to the node, node to bottom edge, or
 * straight through.
 */
export type Edge = { kind: EdgeKind, from: number, to: number, };
