// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileStatus } from "./FileStatus";

/**
 * A commit that changed a file.
 */
export type FileCommit = { oid: string, parents: Array<string>, authorName: string, authorEmail: string, time: number, summary: string, 
/**
 * The file's path in this commit.
 */
path: string, 
/**
 * Its path before, when this commit renamed it.
 */
oldPath: string | null, status: FileStatus, };
