// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileStatus } from "./FileStatus";

export type FileChange = { path: string, 
/**
 * Source path for renames and copies.
 */
oldPath: string | null, status: FileStatus, 
/**
 * `None` for binary files.
 */
additions: number | null, deletions: number | null, };
