// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FlowConfig = { 
/**
 * The production branch.
 */
master: string, 
/**
 * The integration branch.
 */
develop: string, featurePrefix: string, releasePrefix: string, hotfixPrefix: string, 
/**
 * Put in front of release and hotfix names to make their tags.
 */
versionTagPrefix: string, };
