// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitPrefs = { 
/**
 * Fetch every remote of each open repository this often; 0 turns it off.
 */
autoFetchMinutes: number, };
