// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphRow } from "./GraphRow";

export type GraphPage = { start: number, rows: Array<GraphRow>, 
/**
 * Rows computed so far; the total once `complete`.
 */
loaded: number, complete: boolean, maxLanes: number, };
