// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Edge } from "./Edge";
import type { RefLabel } from "./RefLabel";

export type GraphRow = { oid: string, parents: Array<string>, summary: string, authorName: string, authorEmail: string, 
/**
 * Author time, seconds since the Unix epoch.
 */
time: number, refs: Array<RefLabel>, lane: number, edges: Array<Edge>, };
