// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which refs contribute their history to the graph.
 */
export type GraphFilter = { 
/**
 * Full ref names whose history is left out.
 */
hidden: Array<string>, 
/**
 * When non-empty, only these refs are shown and `hidden` is ignored.
 */
solo: Array<string>, };
