// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HeadState = { "kind": "branch", name: string, unborn: boolean, } | { "kind": "detached", oid: string, };
