// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HostedRepo = { 
/**
 * How the service names it: `owner/name` (GitHub, Bitbucket),
 * `group/subgroup/name` (GitLab), `PROJECT/slug` (Bitbucket Server) or
 * `project/name` (Azure DevOps).
 */
path: string, name: string, description: string | null, private: boolean, fork: boolean, cloneHttps: string, cloneSsh: string | null, webUrl: string, defaultBranch: string | null, 
/**
 * Seconds since the Unix epoch.
 */
updated: number | null, };
