// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who git commits as without a profile, to show what empty fields mean.
 */
export type Identity = { name: string | null, email: string | null, signingKey: string | null, };
