// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the signed-in user is involved in a pull request.
 */
export type Involvement = "author" | "reviewer" | "assignee";
