// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Person } from "./Person";

export type Issue = { 
/**
 * The repository (or Jira/Azure project) it belongs to.
 */
repo: string, 
/**
 * What people call it: `#12`, `PROJ-12`.
 */
key: string, number: number, title: string, open: boolean, author: Person | null, labels: Array<string>, webUrl: string, updated: number, };
