// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JournalStep = { label: string, 
/**
 * Why the step can't run, if it can't.
 */
blocked: string | null, };
