// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JournalStep } from "./JournalStep";

/**
 * The next undo and redo steps, for the toolbar.
 */
export type JournalState = { undo: JournalStep | null, redo: JournalStep | null, };
