// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountError } from "./AccountError";
import type { LaunchpadIssue } from "./LaunchpadIssue";
import type { LaunchpadPr } from "./LaunchpadPr";

export type Launchpad = { pullRequests: Array<LaunchpadPr>, issues: Array<LaunchpadIssue>, errors: Array<AccountError>, };
