// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Involvement } from "./Involvement";
import type { PullRequest } from "./PullRequest";

export type LaunchpadPr = { account: string, pr: PullRequest, involvement: Array<Involvement>, };
