// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Issue } from "./Issue";

export type LaunchpadIssue = { account: string, issue: Issue, };
