// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LfsLock = { id: string, path: string, owner: string, 
/**
 * RFC 3339.
 */
lockedAt: string, 
/**
 * Held by the current user; `None` when the server couldn't say.
 */
ours: boolean | null, };
