// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LfsPattern = { 
/**
 * Relative to the repository root.
 */
pattern: string, 
/**
 * The `.gitattributes` file it comes from.
 */
source: string, };
