// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LfsPattern } from "./LfsPattern";

export type LfsStatus = { 
/**
 * `git lfs` is available.
 */
installed: boolean, 
/**
 * Its filters are configured, so tracked files are actually stored in LFS.
 */
initialized: boolean, patterns: Array<LfsPattern>, };
