// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Chosen lines of one hunk, as indices into its `lines`.
 */
export type LineSelection = { hunk: number, lines: Array<number>, };
