// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepoState } from "./RepoState";

export type Local = { 
/**
 * Most recently opened first.
 */
recentRepos: Array<string>, openTabs: Array<string>, activeTab: string | null, 
/**
 * Per-repository state, keyed by repository path.
 */
repos: { [key in string]: RepoState }, };
