// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";
import type { RepoState } from "./RepoState";
import type { SyncSettings } from "./SyncSettings";
import type { Tabs } from "./Tabs";
import type { Workspace } from "./Workspace";

export type Local = { 
/**
 * Most recently opened first.
 */
recentRepos: Array<string>, 
/**
 * Tabs of the active profile.
 */
openTabs: Array<string>, activeTab: string | null, 
/**
 * Per-repository state, keyed by repository path.
 */
repos: { [key in string]: RepoState }, 
/**
 * Id of the profile in use; an unknown id means the first profile.
 */
activeProfile: string, 
/**
 * Tabs of the other profiles, keyed by profile id.
 */
profileTabs: { [key in string]: Tabs }, 
/**
 * Named groups of repositories.
 */
workspaces: Array<Workspace>, 
/**
 * Where the portable settings are synced to, if anywhere.
 */
sync: SyncSettings | null, 
/**
 * Shell for the terminal panel; empty means the platform default.
 */
terminalShell: string, 
/**
 * Accounts on hosting services, each belonging to a profile. Tokens
 * are in the OS keyring, so accounts stay on this machine.
 */
accounts: Array<Account>, };
