// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Upstream } from "./Upstream";

export type LocalBranch = { name: string, fullName: string, oid: string, isHead: boolean, upstream: Upstream | null, };
