// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Part of a merged file. Texts keep their line endings, so concatenating
 * the chosen texts gives the file.
 */
export type MergeChunk = { "kind": "resolved", text: string, } | { "kind": "conflict", ours: string, base: string, theirs: string, };
