// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Involvement } from "./Involvement";
import type { PullRequest } from "./PullRequest";

export type MyPullRequest = { pr: PullRequest, involvement: Array<Involvement>, };
