// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewPullRequest = { title: string, body: string, sourceBranch: string, targetBranch: string, 
/**
 * The fork the source branch is on, if it isn't the target repository.
 */
sourceRepo: string | null, draft: boolean, };
