// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A multi-step git operation waiting for the user.
 */
export type Operation = "merge" | "rebase" | "cherryPick" | "revert" | "applyMailbox" | "bisect";
