// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to do with an operation that stopped part-way.
 */
export type OperationAction = "continue" | "skip" | "abort";
