// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an operation that may stop on conflicts ended.
 */
export type Outcome = "done" | "conflicts";
