// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a partial patch goes.
 */
export type PatchTarget = "stage" | "unstage" | "discard";
