// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitPrefs } from "./GitPrefs";
import type { Profile } from "./Profile";
import type { UiPrefs } from "./UiPrefs";

export type Portable = { ui: UiPrefs, git: GitPrefs, 
/**
 * Command id → shortcuts such as `Mod+Shift+P` (`Mod` is Ctrl, or Cmd
 * on macOS), separated by spaces, replacing the command's defaults.
 * An empty string unbinds it.
 */
keybindings: { [key in string]: string }, 
/**
 * Identities to work as; never empty (the first is the default).
 */
profiles: Array<Profile>, };
