// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SigningFormat } from "./SigningFormat";

/**
 * An identity: who commits are by, how they are signed, and which ssh key
 * is used. Empty fields leave git's own configuration in charge.
 */
export type Profile = { 
/**
 * Stable identifier; also keys the profile's tabs in `local.toml`.
 */
id: string, name: string, userName: string, userEmail: string, 
/**
 * `user.signingKey`: a key id, or for ssh signing a public key path.
 */
signingKey: string, signingFormat: SigningFormat, 
/**
 * Sign every commit and annotated tag; off leaves git's config in charge.
 */
signCommits: boolean, 
/**
 * Private key file for ssh remotes (`core.sshCommand`).
 */
sshKey: string, };
