// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One progress update from a long-running command.
 */
export type Progress = { 
/**
 * E.g. "Receiving objects", or a whole message line from git.
 */
message: string, percent: number | null, };
