// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where git can fetch a pull request's commits from.
 */
export type PrSource = { 
/**
 * A ref on the target repository (`refs/pull/1/head`), else the source
 * branch.
 */
refspec: string, 
/**
 * Fetch from this URL instead of the target repository's remote (the
 * source branch of a fork).
 */
url: string | null, };
