// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How `pull` combines the upstream branch with the current one.
 */
export type PullMode = "default" | "fastForwardOnly" | "merge" | "rebase";
