// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Comment } from "./Comment";
import type { MergeMethod } from "./MergeMethod";
import type { PrSource } from "./PrSource";
import type { PullRequest } from "./PullRequest";
import type { Review } from "./Review";

export type PullRequestDetail = { pr: PullRequest, body: string, headSha: string | null, baseSha: string | null, source: PrSource, 
/**
 * `None` while the service is still working it out.
 */
mergeable: boolean | null, reviews: Array<Review>, comments: Array<Comment>, mergeMethods: Array<MergeMethod>, };
