// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Person } from "./Person";
import type { PrState } from "./PrState";

export type PullRequest = { 
/**
 * The target repository, as [`HostedRepo::path`].
 */
repo: string, number: bigint, title: string, state: PrState, draft: boolean, author: Person, sourceBranch: string, targetBranch: string, 
/**
 * The repository the changes come from, when it's a fork.
 */
sourceRepo: string | null, webUrl: string, updated: number, };
