// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where to push a branch that has no upstream yet.
 */
export type PushTarget = { remote: string, 
/**
 * Branch name on the remote.
 */
branch: string, };
