// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileChange } from "./FileChange";

/**
 * What a pull request changes: from where its branch left the target to
 * its head.
 */
export type RangeDiff = { 
/**
 * The merge base, to diff files against.
 */
base: string, head: string, files: Array<FileChange>, };
