// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A commit an interactive rebase would replay.
 */
export type RebaseCommit = { oid: string, message: string, authorName: string, authorEmail: string, time: number, };
