// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RebaseCommit } from "./RebaseCommit";

/**
 * The commits between `base` and HEAD, oldest first.
 */
export type RebasePlan = { 
/**
 * `None` to rewrite from the root commit.
 */
base: string | null, 
/**
 * HEAD when the plan was made; the rebase refuses to run if it moved.
 */
head: string, commits: Array<RebaseCommit>, 
/**
 * Merge commits in the range; rebasing flattens them away.
 */
merges: number, };
