// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RebaseAction } from "./RebaseAction";

/**
 * One line of the user's plan, in the order to replay.
 */
export type RebaseStep = { oid: string, action: RebaseAction, 
/**
 * The new message for `Reword`, or for the commit a `Squash` produces.
 */
message: string | null, };
