// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RebaseProgress = { 
/**
 * The branch being rebased; `None` for a detached HEAD.
 */
branch: string | null, 
/**
 * The step it stopped at (1-based), of `total`.
 */
step: number, total: number, 
/**
 * The commit it stopped at, abbreviated as git recorded it.
 */
stoppedAt: string | null, 
/**
 * Stopped at an `edit` step so the commit can be amended.
 */
editing: boolean, };
