// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to do with one commit.
 */
export type RebaseAction = "pick" | "reword" | "edit" | "squash" | "fixup" | "drop";
