// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefKind } from "./RefKind";

export type RefLabel = { name: string, fullName: string, kind: RefKind, 
/**
 * The checked-out branch, or HEAD itself when detached.
 */
current: boolean, 
/**
 * For remote branches, the remote's name; `name` is `<remote>/<branch>`.
 */
remote: string | null, };
