// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalBranch } from "./LocalBranch";
import type { Remote } from "./Remote";
import type { Stash } from "./Stash";
import type { Submodule } from "./Submodule";
import type { Tag } from "./Tag";

export type Refs = { local: Array<LocalBranch>, remotes: Array<Remote>, tags: Array<Tag>, stashes: Array<Stash>, submodules: Array<Submodule>, };
