// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteBranch } from "./RemoteBranch";

export type Remote = { name: string, url: string | null, 
/**
 * Only when it differs from `url`.
 */
pushUrl: string | null, branches: Array<RemoteBranch>, };
