// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capabilities } from "./Capabilities";
import type { ProviderKind } from "./ProviderKind";

/**
 * A remote of a local repository that is on one of the accounts' services.
 */
export type RepoLink = { account: string, kind: ProviderKind, remote: string, 
/**
 * The repository on the service, as `HostedRepo::path`.
 */
path: string, capabilities: Capabilities, };
