// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RepoState = { 
/**
 * Full ref names hidden from the graph.
 */
hiddenRefs: Array<string>, 
/**
 * When non-empty, only these refs are shown.
 */
soloRefs: Array<string>, };
