// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepoInfo } from "./RepoInfo";

/**
 * An at-a-glance state of a repository, for lists of many repositories.
 */
export type RepoSummary = { info: RepoInfo, 
/**
 * The current branch's upstream, e.g. `origin/main`.
 */
upstream: string | null, ahead: number, behind: number, staged: number, 
/**
 * Changed and untracked files (an untracked directory counts once).
 */
unstaged: number, conflicted: number, };
