// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeadState } from "./HeadState";

export type RepoInfo = { 
/**
 * Working tree root, or the git dir for bare repositories.
 */
path: string, name: string, isBare: boolean, head: HeadState, };
