// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeadState } from "./HeadState";
import type { Operation } from "./Operation";
import type { RebaseProgress } from "./RebaseProgress";

export type RepoInfo = { 
/**
 * Working tree root, or the git dir for bare repositories.
 */
path: string, name: string, isBare: boolean, head: HeadState, 
/**
 * A merge, rebase, … that stopped part-way, e.g. on conflicts.
 */
operation: Operation | null, 
/**
 * Where a stopped rebase is.
 */
rebase: RebaseProgress | null, };
