// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How to resolve a conflicted file.
 */
export type Resolution = { "kind": "content", text: string, } | { "kind": "ours" } | { "kind": "theirs" } | { "kind": "delete" };
