// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Person } from "./Person";
import type { ReviewState } from "./ReviewState";

export type Review = { author: Person, state: ReviewState, };
