// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Signature = { name: string, email: string, 
/**
 * Seconds since the Unix epoch.
 */
time: number, };
