// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";

export type SignIn = { account: Account, 
/**
 * Set when the token could not be saved for later sessions.
 */
warning: string | null, };
