// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SshKey = { 
/**
 * File name of the private key, e.g. `id_ed25519`.
 */
name: string, 
/**
 * Path of the private key; the public key is this plus `.pub`.
 */
path: string, hasPrivate: boolean, 
/**
 * The public key line, as it would be pasted into a hosting service.
 */
publicKey: string, algorithm: string, comment: string, 
/**
 * `SHA256:…`, as `ssh-keygen -l` shows it.
 */
fingerprint: string, };
