// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StashOptions = { message: string | null, includeUntracked: boolean, 
/**
 * Leave staged changes in place as well as stashing them.
 */
keepIndex: boolean, };
