// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileStatus } from "./FileStatus";
import type { SubmoduleChange } from "./SubmoduleChange";

export type StatusEntry = { path: string, 
/**
 * Source path of a staged rename or copy.
 */
oldPath: string | null, status: FileStatus, 
/**
 * Set when the path is a submodule.
 */
submodule: SubmoduleChange | null, };
