// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubmoduleState } from "./SubmoduleState";

export type Submodule = { name: string, path: string, state: SubmoduleState, };
