// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a submodule's checkout compares with the commit the superproject
 * records for it.
 */
export type SubmoduleState = "uninitialized" | "current" | "moved" | "conflicted";
