// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubmoduleChange = { 
/**
 * The submodule's checked-out commit differs from the recorded one.
 */
commitChanged: boolean, 
/**
 * Tracked files inside the submodule are modified.
 */
modified: boolean, 
/**
 * The submodule has untracked files.
 */
untracked: boolean, };
