// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncSettings = { 
/**
 * A private repository the user owns.
 */
remote: string, branch: string, 
/**
 * Push committed changes this often (they are also pushed on exit).
 */
pushMinutes: number, };
