// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Change } from "./Change";
import type { SyncSettings } from "./SyncSettings";

/**
 * What the UI shows about sync.
 */
export type SyncStatus = { 
/**
 * `None` while sync is off.
 */
settings: SyncSettings | null, running: boolean, 
/**
 * When the last sync finished, in seconds since the Unix epoch.
 */
lastSync: number | null, error: string | null, 
/**
 * Settings changed differently here (`current`) and on another
 * machine (`incoming`), waiting for a choice.
 */
conflicts: Array<Change>, };
