// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Tag = { name: string, fullName: string, 
/**
 * The object the tag ultimately points at (annotated tags are peeled).
 */
oid: string, };
