// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffView } from "./DiffView";
import type { Theme } from "./Theme";

export type UiPrefs = { theme: Theme, 
/**
 * Fetch author avatars from Gravatar (sends a hash of the email address).
 */
showAvatars: boolean, diffView: DiffView, ignoreWhitespace: boolean, 
/**
 * Changed files as a folder tree rather than a flat list.
 */
fileTree: boolean, 
/**
 * Width of the graph column in pixels; 0 sizes it to the lanes.
 */
graphWidth: number, terminalFontSize: number, 
/**
 * Short sounds when an action succeeds or fails. Off by default.
 */
sounds: boolean, };
