// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffView } from "./DiffView";
import type { Theme } from "./Theme";

export type UiPrefs = { theme: Theme, 
/**
 * Fetch author avatars from Gravatar (sends a hash of the email address).
 */
showAvatars: boolean, diffView: DiffView, ignoreWhitespace: boolean, };
