// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Upstream = { 
/**
 * Short name, e.g. `origin/main`.
 */
name: string, ahead: number, behind: number, 
/**
 * The upstream branch was deleted on the remote.
 */
gone: boolean, };
