// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The signed-in user.
 */
export type User = { 
/**
 * The service's own id.
 */
id: string, username: string, name: string, avatarUrl: string | null, 
/**
 * Some services (Bitbucket Server) key users by a slug.
 */
slug: string, };
