// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Worktree = { path: string, 
/**
 * `None` before the first commit.
 */
head: string | null, 
/**
 * The checked-out branch (short name); `None` when detached.
 */
branch: string | null, 
/**
 * The repository's main working tree (or the bare repository itself).
 */
isMain: boolean, 
/**
 * The working tree this repository was opened from.
 */
isCurrent: boolean, bare: boolean, 
/**
 * Why it is locked, if it is (possibly an empty reason).
 */
locked: string | null, 
/**
 * Its directory is gone; `prune` would forget it.
 */
prunable: boolean, };
