// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatusEntry } from "./StatusEntry";

/**
 * Uncommitted changes, split the way `git status` shows them.
 */
export type WorkingStatus = { 
/**
 * Changes in the index, relative to HEAD.
 */
staged: Array<StatusEntry>, 
/**
 * Changes in the working tree relative to the index, and untracked files.
 */
unstaged: Array<StatusEntry>, 
/**
 * Unmerged paths. They are neither staged nor unstaged until resolved.
 */
conflicted: Array<StatusEntry>, };
