// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Workspace = { name: string, 
/**
 * Repository paths, in the order shown.
 */
repos: Array<string>, };
