//! Profiles change who git commits as, how it signs and which ssh key it
//! uses, without touching the user's own git configuration: git runs with
//! `GIT_CONFIG_GLOBAL` pointing at a generated file that includes the
//! user's global config and then overrides a few keys. Repository config
//! still wins over it, exactly as it wins over the global config.

use std::ffi::OsString;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use ronin_config::{Profile, SigningFormat};
use ronin_git::{GitCli, GitVersion};

/// `GIT_CONFIG_GLOBAL` appeared in git 2.32.
const MIN_VERSION: GitVersion = GitVersion {
    major: 2,
    minor: 32,
    patch: 0,
};

pub struct ProfileGit {
    home: PathBuf,
    /// The user's own global config files, in the order git reads them.
    globals: Vec<PathBuf>,
    /// The generated file, when the active profile overrides anything.
    config: Option<PathBuf>,
}

impl ProfileGit {
    pub fn new(home: PathBuf) -> Self {
        // The app never sets GIT_CONFIG_GLOBAL on itself, only on the
        // commands it runs, so this is always the user's own setting.
        let globals = match std::env::var_os("GIT_CONFIG_GLOBAL") {
            Some(path) => vec![PathBuf::from(path)],
            None => {
                let xdg = std::env::var_os("XDG_CONFIG_HOME")
                    .filter(|v| !v.is_empty())
                    .map_or_else(|| home.join(".config"), PathBuf::from);
                vec![xdg.join("git").join("config"), home.join(".gitconfig")]
            }
        };
        Self {
            home,
            globals,
            config: None,
        }
    }

    pub fn apply(&self, git: GitCli) -> GitCli {
        match &self.config {
            Some(path) => git.env("GIT_CONFIG_GLOBAL", path),
            None => git,
        }
    }

    /// Environment for other programs that run git, such as the terminal.
    pub fn env(&self) -> Option<(&'static str, OsString)> {
        self.config
            .as_ref()
            .map(|p| ("GIT_CONFIG_GLOBAL", p.clone().into_os_string()))
    }

    pub fn home(&self) -> &Path {
        &self.home
    }

    /// Makes `profile` the one git runs as, writing its config file under
    /// `dir`. On failure git runs with the user's own configuration.
    pub fn activate(
        &mut self,
        dir: &Path,
        profile: &Profile,
        version: GitVersion,
    ) -> Result<(), String> {
        self.config = None;
        if !profile.overrides_git() {
            return Ok(());
        }
        if version < MIN_VERSION {
            return Err(format!(
                "Profile “{}” needs git {MIN_VERSION} or newer to change your identity; \
                 git {version} uses its own configuration.",
                profile.name
            ));
        }
        let path = dir
            .join("profiles")
            .join(format!("{}.gitconfig", file_name(&profile.id)));
        let text = gitconfig(profile, &self.globals, &self.home);
        write(&path, &text).map_err(|e| format!("could not write {}: {e}", path.display()))?;
        self.config = Some(path);
        Ok(())
    }
}

fn write(path: &Path, text: &str) -> std::io::Result<()> {
    std::fs::create_dir_all(path.parent().expect("the file is in a directory"))?;
    let tmp = path.with_extension("tmp");
    std::fs::write(&tmp, text)?;
    std::fs::rename(&tmp, path)
}

/// Profile ids come from settings files; keep them to safe file names.
fn file_name(id: &str) -> String {
    id.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

/// The config file for `profile`: the user's global files, then the
/// profile's overrides.
pub fn gitconfig(profile: &Profile, globals: &[PathBuf], home: &Path) -> String {
    let mut out = format!(
        "# Generated by Git Ronin for profile “{}”. Changes are overwritten.\n",
        profile.name.replace(['\n', '\r'], " ")
    );
    for global in globals {
        // A missing include is silently skipped.
        let _ = writeln!(
            out,
            "[include]\n\tpath = {}",
            quote(&global.to_string_lossy())
        );
    }
    let mut section = |name: &str, entries: &[(&str, String)]| {
        let entries: Vec<_> = entries.iter().filter(|(_, v)| !v.is_empty()).collect();
        if entries.is_empty() {
            return;
        }
        let _ = writeln!(out, "[{name}]");
        for (key, value) in entries {
            let _ = writeln!(out, "\t{key} = {}", quote(value));
        }
    };
    let signing_key = if profile.signing_format == SigningFormat::Ssh {
        expand(&profile.signing_key, home)
    } else {
        profile.signing_key.trim().to_owned()
    };
    section(
        "user",
        &[
            ("name", profile.user_name.trim().to_owned()),
            ("email", profile.user_email.trim().to_owned()),
            ("signingKey", signing_key.clone()),
        ],
    );
    if profile.sign_commits || !signing_key.is_empty() {
        let format = match profile.signing_format {
            SigningFormat::Openpgp => "openpgp",
            SigningFormat::Ssh => "ssh",
            SigningFormat::X509 => "x509",
        };
        section("gpg", &[("format", format.to_owned())]);
    }
    if profile.sign_commits {
        section("commit", &[("gpgSign", "true".to_owned())]);
        section("tag", &[("gpgSign", "true".to_owned())]);
    }
    let ssh_key = expand(&profile.ssh_key, home);
    if !ssh_key.is_empty() {
        // git runs this through a shell, also on Windows.
        let command = format!(
            "ssh -i '{}' -o IdentitiesOnly=yes",
            ssh_key.replace('\\', "/").replace('\'', r"'\''")
        );
        section("core", &[("sshCommand", command)]);
    }
    out
}

/// A config value in double quotes, which keeps spaces, `#` and `;`.
fn quote(value: &str) -> String {
    let escaped = value
        .replace(['\n', '\r'], " ")
        .replace('\\', "\\\\")
        .replace('"', "\\\"");
    format!("\"{escaped}\"")
}

/// Expands a leading `~` to the home directory.
fn expand(path: &str, home: &Path) -> String {
    let path = path.trim();
    match path.strip_prefix("~/").or(path.strip_prefix("~\\")) {
        Some(rest) => home.join(rest).to_string_lossy().into_owned(),
        None if path == "~" => home.to_string_lossy().into_owned(),
        None => path.to_owned(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn git() -> GitCli {
        GitCli::discover().unwrap()
    }

    fn work() -> Profile {
        Profile {
            id: "work".into(),
            name: "Work".into(),
            user_name: "Jo Doe".into(),
            user_email: "jo@work.example".into(),
            signing_key: "~/.ssh/id_work.pub".into(),
            signing_format: SigningFormat::Ssh,
            sign_commits: true,
            ssh_key: "~/.ssh/id_work".into(),
        }
    }

    fn get(git: &GitCli, cwd: &Path, key: &str) -> String {
        git.run(cwd, ["config", "--get", key])
            .unwrap()
            .trim()
            .to_owned()
    }

    #[test]
    fn overrides_identity_on_top_of_the_users_global_config() {
        let tmp = tempfile::tempdir().unwrap();
        let home = tmp.path().join("home dir");
        std::fs::create_dir_all(&home).unwrap();
        let global = home.join(".gitconfig");
        std::fs::write(
            &global,
            "[user]\n\tname = Personal\n\temail = me@home.example\n[alias]\n\tst = status\n",
        )
        .unwrap();

        let mut profile = ProfileGit {
            home: home.clone(),
            globals: vec![home.join("missing"), global],
            config: None,
        };
        profile
            .activate(tmp.path(), &work(), git().version())
            .unwrap();
        let git = profile.apply(git()).env("GIT_CONFIG_NOSYSTEM", "1");

        assert_eq!(get(&git, tmp.path(), "user.name"), "Jo Doe");
        assert_eq!(get(&git, tmp.path(), "user.email"), "jo@work.example");
        // The user's other settings still apply.
        assert_eq!(get(&git, tmp.path(), "alias.st"), "status");
        assert_eq!(get(&git, tmp.path(), "gpg.format"), "ssh");
        assert_eq!(get(&git, tmp.path(), "commit.gpgsign"), "true");
        assert_eq!(
            get(&git, tmp.path(), "user.signingkey"),
            home.join(".ssh/id_work.pub").to_string_lossy()
        );
        let ssh = get(&git, tmp.path(), "core.sshcommand");
        assert!(
            ssh.starts_with("ssh -i '") && ssh.contains("home dir"),
            "{ssh}"
        );

        // Repository config still wins.
        let repo = tmp.path().join("repo");
        git.run(tmp.path(), ["init", "-q", "repo"]).unwrap();
        git.run(&repo, ["config", "user.email", "repo@example"])
            .unwrap();
        assert_eq!(get(&git, &repo, "user.email"), "repo@example");
    }

    #[test]
    fn a_profile_without_overrides_leaves_git_alone() {
        let tmp = tempfile::tempdir().unwrap();
        let mut profile = ProfileGit::new(tmp.path().to_owned());
        profile
            .activate(tmp.path(), &Profile::default(), git().version())
            .unwrap();
        assert!(profile.env().is_none());
        assert!(!tmp.path().join("profiles").exists());

        let old = GitVersion {
            major: 2,
            minor: 31,
            patch: 0,
        };
        assert!(profile.activate(tmp.path(), &work(), old).is_err());
        assert!(profile.env().is_none());
    }

    #[test]
    fn quotes_values_and_file_names() {
        assert_eq!(quote(r#"a "b" \c"#), r#""a \"b\" \\c""#);
        assert_eq!(file_name("../x y"), "___x_y");
        let home = Path::new("/h");
        assert_eq!(expand("~/k", home), home.join("k").to_string_lossy());
        assert_eq!(expand("/abs", home), "/abs");
    }
}
